---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
  - name: Install packages on Centos
    yum:
       name: "{{item}}"
       state: present
    when: ansible_distribution == "CentOS"
    loop:
      - ntp
      - wget
      - git
      - zip
      - unzip

  - name: Update apt package cache
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install packages on Ubuntu
    apt:
       name: "{{item}}"
       state: present
    when: ansible_distribution == "Ubuntu"
    loop:
      - ntp
      - wget
      - git
      - zip
      - unzip

  - name: Start & enable NTP on Centos
    service:
      name: ntpd
      enabled: yes
      state: started
    when: ansible_distribution == "CentOS"

  - name: Start & enable NTP on Ubuntu
    service:
      name: ntp
      enabled: yes
      state: started
    when: ansible_os_family == "Debian"

  - name: Add group
    group:
      name: devops
      state: present

  - name: Add users
    user:
      name: "{{item}}" 
      state:  present
      groups: devops
    loop:
     - user1
     - user2
     - user3
