---
- name: Provisioning Server
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.java

    - role:  post-install 
      vars:  
        ntp0: 0.in.pool.ntp.org
        ntp1: 1.in.pool.ntp.org
        ntp2: 2.in.pool.ntp.org

